name: CI

on:
  push:
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up uv
        uses: astral-sh/setup-uv@v5

      - name: install dependencies
        run: |
          uv pip install --system flake8 "black[jupyter]" isort

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

      - name: lint with isort
        run: |
          isort --check .

  test:

      runs-on: ubuntu-latest

      steps:

        - name: get repo
          uses: actions/checkout@v3

        - name: set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - run: HEAVYEDGE_TEST_MODE=1 ./setup.sh
          env:
            HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
            LABELS_V2_GDRIVE: ${{ secrets.LABELS_V2_GDRIVE }}

        - name: build models and examples
          run: HEAVYEDGE_TEST_MODE=1 make

        - name: test models
          run: HEAVYEDGE_TEST_MODE=1 make tests

        - uses: actions/upload-artifact@v4
          with:
            name: train-data
            path: |
              _data/v2/profiles/mean_profiles/dataset5/*
              _data/v2/labels/dataset5/*
            retention-days: 1

        - uses: actions/upload-artifact@v4
          with:
            name: trained-models
            path: models
            retention-days: 1
